export interface ProductJSON {
	ID: number;
	Type: string;
	SKU: string;
	Name: string;
	Published: number;
	"Is featured?": number;
	"Short description": string;
	Description: string;
	"In stock?": number;
	Stock: string | number;
	"Backorders allowed?": number;
	"Sold individually?": number;
	"Weight (kg)": number;
	"Length (cm)": number;
	"Width (cm)": number;
	"Height (cm)": number;
	"Allow customer reviews?": number;
	"Purchase note": string;
	"Sale price": string;
	"Regular price": string;
	Categories: string;
	Tags: string;
	"Shipping class": string;
	Images: string;
	Parent: string;
	Upsells: string;
	"Cross-sells": string;
	Position: number;
	"Swatches Attributes": string;
	"Attribute 1 name": string;
	"Attribute 1 value(s)": string;
	"Attribute 1 visible": number;
	"Attribute 1 global": number;
	"Attribute 1 default": string;
	"Attribute 2 name": string;
	"Attribute 2 value(s)": string;
	"Attribute 2 visible": number;
	"Attribute 2 global": number;
	"Attribute 2 default": string;
	"Attribute 3 name": string;
	"Attribute 3 value(s)": string;
	"Attribute 3 visible": number;
	"Attribute 3 global": number;
	"Attribute 3 default": string;
	"Attribute 4 name": string;
	"Attribute 4 value(s)": string;
	"Attribute 4 visible": number;
	"Attribute 4 global": number;
	"Attribute 4 default": string;
	"Attribute 5 name": string;
	"Attribute 5 value(s)": string;
	"Attribute 5 visible": number;
	"Attribute 5 global": number;
	"Attribute 5 default": string;
	"Attribute 6 name": string;
	"Attribute 6 value(s)": string;
	"Attribute 6 visible": number;
	"Attribute 6 global": number;
	"Attribute 6 default": string;
	"Attribute 7 name": string;
	"Attribute 7 value(s)": string;
	"Attribute 7 visible": number;
	"Attribute 7 global": number;
	"Attribute 7 default": string;
	"Attribute 8 name": string;
	"Attribute 8 value(s)": string;
	"Attribute 8 visible": number;
	"Attribute 8 global": number;
	"Attribute 8 default": string;
	"Meta: _wpm_gtin_code": string;
	"Meta: _judgeme_api_registered": number;
	"Meta: _wpsso_head_info_schema_type": string;
	"Meta: _wpsso_head_info_og_type": string;
	"Meta: _wpsso_head_info_og_img_thumb": string;
	"Meta: _wpsso_head_info_og_desc": string;
	"Meta: rank_math_permalink": string;
	"Meta: rank_math_twitter_card_type": string;
	"Meta: rank_math_title": string;
	"Meta: rank_math_description": string;
	"Meta: fb_product_group_id": number;
	"Meta: fb_visibility": string;
	"Meta: upsell_present": string;
	"Meta: rank_math_focus_keyword": string;
	"Meta: product_title_in_category_page": string;
	"Meta: size_chart_desc": string;
	"Meta: fb_product_item_id": string | number;
	"Meta: rank_math_canonical_url": string;
	[key: string]: any;
}

export interface ProductCSV {
	"Product Id"?: string;
	"Product Handle": string;
	"Product Title": string;
	"Product Subtitle": string;
	"Product Description": string;
	"Product Status": string;
	"Product Thumbnail": string;
	"Product Weight": string;
	"Product Length": string;
	"Product Width": string;
	"Product Height": string;
	"Product HS Code"?: string;
	"Product Origin Country"?: string;
	"Product MID Code"?: string;
	"Product Material"?: string;
	"Product Collection Title"?: string;
	"Product Collection Handle"?: string;
	"Product Type"?: string;
	"Product Tags"?: string;
	"Product Discountable"?: boolean;
	"Product External Id"?: string;
	"Product Profile Name"?: string;
	"Product Profile Type"?: string;
	"Product Sales Channel 1": string;
	"Variant Id"?: string;
	"Variant Title": string;
	"Variant SKU": string;
	"Variant Barcode"?: string;
	"Variant Inventory Quantity"?: number;
	"Variant Allow Backorder"?: boolean;
	"Variant Manage Inventory"?: boolean;
	"Variant Weight"?: number;
	"Variant Length"?: number;
	"Variant Width"?: number;
	"Variant Height"?: number;
	"Variant HS Code"?: string;
	"Variant Origin Country"?: string;
	"Variant MID Code"?: string;
	"Variant Material"?: string;
	"Price EUR"?: string;
	"Price USD"?: string;
	"Price BRL"?: string;
	"Product Categories"?: string;
	"Option 1 Name"?: string;
	"Option 1 Value"?: string;
	"Option 2 Name"?: string;
	"Option 2 Value"?: string;
	"Option 3 Name"?: string;
	"Option 3 Value"?: string;
	"Option 4 Name"?: string;
	"Option 4 Value"?: string;
	"Option 5 Name"?: string;
	"Option 5 Value"?: string;
	"Option 6 Name"?: string;
	"Option 6 Value"?: string;
	"Option 7 Name"?: string;
	"Option 7 Value"?: string;
	"Option 8 Name"?: string;
	"Option 8 Value"?: string;
	"Image 1 Url"?: string;
	"Image 2 Url"?: string;
	"Image 3 Url"?: string;
	"Image 4 Url"?: string;
	"Image 5 Url"?: string;
	"Image 6 Url"?: string;
	"Image 7 Url"?: string;
	"Image 8 Url"?: string;
}
